#!/usr/bin/env python3
"""Regenerate the bundled icon font and qml/Icons.js from Lucide (ISC license).

Only the icons listed below are kept, so the font stays small. To add an icon:
add "app-name lucide-name" to ICONS, then run

    npm pack lucide-static && tar xzf lucide-static-*.tgz
    python3 -m pip install fonttools
    python3 tools/icons.py package

One icon per meaning: reuse an existing app name before adding a new one.
"""
import json
import pathlib
import sys

ICONS = """
close x
add plus
minus minus
more ellipsis
reload rotate-cw
reset rotate-ccw
down chevron-down
up chevron-up
left chevron-left
right chevron-right
back chevron-left
forward chevron-right
copy copy
trash trash-2
restore undo-2
link link
external external-link
folder folder
open folder-open
search search
edit pencil
send arrow-up
stop square
attach paperclip
star star
ai sparkles
capture scan
highlight highlighter
draw pen-line
comment message-square
text type
image image
excerpt quote
outline list-tree
thumbnails layout-grid
related network
split columns-2
splitDown rows-2
preview eye
check check
home house
library library
globe globe
note square-pen
document file-text
download download
print printer
export file-down
pause pause
play play
fast zap
effort gauge
key key-round
settings settings
locate file-search
tag tag
workspace layers
appearance palette
keyboard keyboard
data database
reading book-open
alert circle-alert
ok circle-check
filter list-filter
history history
"""

def main(package: pathlib.Path) -> None:
    from fontTools import subset

    root = pathlib.Path(__file__).resolve().parent.parent
    codepoints = json.loads((package / "font" / "codepoints.json").read_text())
    pairs = [line.split() for line in ICONS.strip().splitlines()]
    glyphs = {app: codepoints[lucide] for app, lucide in pairs}
    out = root / "resources" / "icons"
    out.mkdir(parents=True, exist_ok=True)
    options = subset.Options()
    options.layout_features = []
    options.name_IDs = ["*"]
    font = subset.load_font(str(package / "font" / "lucide.ttf"), options)
    subsetter = subset.Subsetter(options)
    subsetter.populate(unicodes=sorted(set(glyphs.values())))
    subsetter.subset(font)
    subset.save_font(font, str(out / "lucide.ttf"), options)
    (out / "LICENSE").write_text((package / "LICENSE").read_text())
    entries = ",\n".join(f'    "{app}": "\\u{cp:04x}"' for app, cp in glyphs.items())
    (root / "style" / "Icons.js").write_text(
        ".pragma library\n\n"
        "// Generated by tools/icons.py from Lucide (resources/icons/LICENSE). App name → glyph.\n"
        f"var glyphs = {{\n{entries}\n}}\n"
        'function glyph(name) { return glyphs[name] || "" }\n'
    )
    print(f"{len(glyphs)} icons, {(out / 'lucide.ttf').stat().st_size} bytes")


if __name__ == "__main__":
    main(pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "package"))
